# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/work/github/EasyNet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/work/github/EasyNet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/work/github/EasyNet/CMakeFiles /home/kevin/work/github/EasyNet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/work/github/EasyNet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EasyNet

# Build rule for target.
EasyNet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EasyNet
.PHONY : EasyNet

# fast build rule for target.
EasyNet/fast:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/build
.PHONY : EasyNet/fast

#=============================================================================
# Target rules for targets named ChatClient

# Build rule for target.
ChatClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ChatClient
.PHONY : ChatClient

# fast build rule for target.
ChatClient/fast:
	$(MAKE) -f CMakeFiles/ChatClient.dir/build.make CMakeFiles/ChatClient.dir/build
.PHONY : ChatClient/fast

#=============================================================================
# Target rules for targets named ChatServer

# Build rule for target.
ChatServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ChatServer
.PHONY : ChatServer

# fast build rule for target.
ChatServer/fast:
	$(MAKE) -f CMakeFiles/ChatServer.dir/build.make CMakeFiles/ChatServer.dir/build
.PHONY : ChatServer/fast

EasyNet/src/base/Condition.o: EasyNet/src/base/Condition.cpp.o

.PHONY : EasyNet/src/base/Condition.o

# target to build an object file
EasyNet/src/base/Condition.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/Condition.cpp.o
.PHONY : EasyNet/src/base/Condition.cpp.o

EasyNet/src/base/Condition.i: EasyNet/src/base/Condition.cpp.i

.PHONY : EasyNet/src/base/Condition.i

# target to preprocess a source file
EasyNet/src/base/Condition.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/Condition.cpp.i
.PHONY : EasyNet/src/base/Condition.cpp.i

EasyNet/src/base/Condition.s: EasyNet/src/base/Condition.cpp.s

.PHONY : EasyNet/src/base/Condition.s

# target to generate assembly for a file
EasyNet/src/base/Condition.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/Condition.cpp.s
.PHONY : EasyNet/src/base/Condition.cpp.s

EasyNet/src/base/MutexLock.o: EasyNet/src/base/MutexLock.cpp.o

.PHONY : EasyNet/src/base/MutexLock.o

# target to build an object file
EasyNet/src/base/MutexLock.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/MutexLock.cpp.o
.PHONY : EasyNet/src/base/MutexLock.cpp.o

EasyNet/src/base/MutexLock.i: EasyNet/src/base/MutexLock.cpp.i

.PHONY : EasyNet/src/base/MutexLock.i

# target to preprocess a source file
EasyNet/src/base/MutexLock.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/MutexLock.cpp.i
.PHONY : EasyNet/src/base/MutexLock.cpp.i

EasyNet/src/base/MutexLock.s: EasyNet/src/base/MutexLock.cpp.s

.PHONY : EasyNet/src/base/MutexLock.s

# target to generate assembly for a file
EasyNet/src/base/MutexLock.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/MutexLock.cpp.s
.PHONY : EasyNet/src/base/MutexLock.cpp.s

EasyNet/src/base/Thread.o: EasyNet/src/base/Thread.cpp.o

.PHONY : EasyNet/src/base/Thread.o

# target to build an object file
EasyNet/src/base/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/Thread.cpp.o
.PHONY : EasyNet/src/base/Thread.cpp.o

EasyNet/src/base/Thread.i: EasyNet/src/base/Thread.cpp.i

.PHONY : EasyNet/src/base/Thread.i

# target to preprocess a source file
EasyNet/src/base/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/Thread.cpp.i
.PHONY : EasyNet/src/base/Thread.cpp.i

EasyNet/src/base/Thread.s: EasyNet/src/base/Thread.cpp.s

.PHONY : EasyNet/src/base/Thread.s

# target to generate assembly for a file
EasyNet/src/base/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/Thread.cpp.s
.PHONY : EasyNet/src/base/Thread.cpp.s

EasyNet/src/base/TimeStamp.o: EasyNet/src/base/TimeStamp.cpp.o

.PHONY : EasyNet/src/base/TimeStamp.o

# target to build an object file
EasyNet/src/base/TimeStamp.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/TimeStamp.cpp.o
.PHONY : EasyNet/src/base/TimeStamp.cpp.o

EasyNet/src/base/TimeStamp.i: EasyNet/src/base/TimeStamp.cpp.i

.PHONY : EasyNet/src/base/TimeStamp.i

# target to preprocess a source file
EasyNet/src/base/TimeStamp.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/TimeStamp.cpp.i
.PHONY : EasyNet/src/base/TimeStamp.cpp.i

EasyNet/src/base/TimeStamp.s: EasyNet/src/base/TimeStamp.cpp.s

.PHONY : EasyNet/src/base/TimeStamp.s

# target to generate assembly for a file
EasyNet/src/base/TimeStamp.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/base/TimeStamp.cpp.s
.PHONY : EasyNet/src/base/TimeStamp.cpp.s

EasyNet/src/net/Acceptor.o: EasyNet/src/net/Acceptor.cpp.o

.PHONY : EasyNet/src/net/Acceptor.o

# target to build an object file
EasyNet/src/net/Acceptor.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Acceptor.cpp.o
.PHONY : EasyNet/src/net/Acceptor.cpp.o

EasyNet/src/net/Acceptor.i: EasyNet/src/net/Acceptor.cpp.i

.PHONY : EasyNet/src/net/Acceptor.i

# target to preprocess a source file
EasyNet/src/net/Acceptor.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Acceptor.cpp.i
.PHONY : EasyNet/src/net/Acceptor.cpp.i

EasyNet/src/net/Acceptor.s: EasyNet/src/net/Acceptor.cpp.s

.PHONY : EasyNet/src/net/Acceptor.s

# target to generate assembly for a file
EasyNet/src/net/Acceptor.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Acceptor.cpp.s
.PHONY : EasyNet/src/net/Acceptor.cpp.s

EasyNet/src/net/Channel.o: EasyNet/src/net/Channel.cpp.o

.PHONY : EasyNet/src/net/Channel.o

# target to build an object file
EasyNet/src/net/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Channel.cpp.o
.PHONY : EasyNet/src/net/Channel.cpp.o

EasyNet/src/net/Channel.i: EasyNet/src/net/Channel.cpp.i

.PHONY : EasyNet/src/net/Channel.i

# target to preprocess a source file
EasyNet/src/net/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Channel.cpp.i
.PHONY : EasyNet/src/net/Channel.cpp.i

EasyNet/src/net/Channel.s: EasyNet/src/net/Channel.cpp.s

.PHONY : EasyNet/src/net/Channel.s

# target to generate assembly for a file
EasyNet/src/net/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Channel.cpp.s
.PHONY : EasyNet/src/net/Channel.cpp.s

EasyNet/src/net/ChannelBuffer.o: EasyNet/src/net/ChannelBuffer.cpp.o

.PHONY : EasyNet/src/net/ChannelBuffer.o

# target to build an object file
EasyNet/src/net/ChannelBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/ChannelBuffer.cpp.o
.PHONY : EasyNet/src/net/ChannelBuffer.cpp.o

EasyNet/src/net/ChannelBuffer.i: EasyNet/src/net/ChannelBuffer.cpp.i

.PHONY : EasyNet/src/net/ChannelBuffer.i

# target to preprocess a source file
EasyNet/src/net/ChannelBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/ChannelBuffer.cpp.i
.PHONY : EasyNet/src/net/ChannelBuffer.cpp.i

EasyNet/src/net/ChannelBuffer.s: EasyNet/src/net/ChannelBuffer.cpp.s

.PHONY : EasyNet/src/net/ChannelBuffer.s

# target to generate assembly for a file
EasyNet/src/net/ChannelBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/ChannelBuffer.cpp.s
.PHONY : EasyNet/src/net/ChannelBuffer.cpp.s

EasyNet/src/net/EventLoop.o: EasyNet/src/net/EventLoop.cpp.o

.PHONY : EasyNet/src/net/EventLoop.o

# target to build an object file
EasyNet/src/net/EventLoop.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoop.cpp.o
.PHONY : EasyNet/src/net/EventLoop.cpp.o

EasyNet/src/net/EventLoop.i: EasyNet/src/net/EventLoop.cpp.i

.PHONY : EasyNet/src/net/EventLoop.i

# target to preprocess a source file
EasyNet/src/net/EventLoop.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoop.cpp.i
.PHONY : EasyNet/src/net/EventLoop.cpp.i

EasyNet/src/net/EventLoop.s: EasyNet/src/net/EventLoop.cpp.s

.PHONY : EasyNet/src/net/EventLoop.s

# target to generate assembly for a file
EasyNet/src/net/EventLoop.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoop.cpp.s
.PHONY : EasyNet/src/net/EventLoop.cpp.s

EasyNet/src/net/EventLoopThread.o: EasyNet/src/net/EventLoopThread.cpp.o

.PHONY : EasyNet/src/net/EventLoopThread.o

# target to build an object file
EasyNet/src/net/EventLoopThread.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoopThread.cpp.o
.PHONY : EasyNet/src/net/EventLoopThread.cpp.o

EasyNet/src/net/EventLoopThread.i: EasyNet/src/net/EventLoopThread.cpp.i

.PHONY : EasyNet/src/net/EventLoopThread.i

# target to preprocess a source file
EasyNet/src/net/EventLoopThread.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoopThread.cpp.i
.PHONY : EasyNet/src/net/EventLoopThread.cpp.i

EasyNet/src/net/EventLoopThread.s: EasyNet/src/net/EventLoopThread.cpp.s

.PHONY : EasyNet/src/net/EventLoopThread.s

# target to generate assembly for a file
EasyNet/src/net/EventLoopThread.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoopThread.cpp.s
.PHONY : EasyNet/src/net/EventLoopThread.cpp.s

EasyNet/src/net/EventLoopThreadGroup.o: EasyNet/src/net/EventLoopThreadGroup.cpp.o

.PHONY : EasyNet/src/net/EventLoopThreadGroup.o

# target to build an object file
EasyNet/src/net/EventLoopThreadGroup.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoopThreadGroup.cpp.o
.PHONY : EasyNet/src/net/EventLoopThreadGroup.cpp.o

EasyNet/src/net/EventLoopThreadGroup.i: EasyNet/src/net/EventLoopThreadGroup.cpp.i

.PHONY : EasyNet/src/net/EventLoopThreadGroup.i

# target to preprocess a source file
EasyNet/src/net/EventLoopThreadGroup.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoopThreadGroup.cpp.i
.PHONY : EasyNet/src/net/EventLoopThreadGroup.cpp.i

EasyNet/src/net/EventLoopThreadGroup.s: EasyNet/src/net/EventLoopThreadGroup.cpp.s

.PHONY : EasyNet/src/net/EventLoopThreadGroup.s

# target to generate assembly for a file
EasyNet/src/net/EventLoopThreadGroup.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/EventLoopThreadGroup.cpp.s
.PHONY : EasyNet/src/net/EventLoopThreadGroup.cpp.s

EasyNet/src/net/FixedLengthFrameCodec.o: EasyNet/src/net/FixedLengthFrameCodec.cpp.o

.PHONY : EasyNet/src/net/FixedLengthFrameCodec.o

# target to build an object file
EasyNet/src/net/FixedLengthFrameCodec.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/FixedLengthFrameCodec.cpp.o
.PHONY : EasyNet/src/net/FixedLengthFrameCodec.cpp.o

EasyNet/src/net/FixedLengthFrameCodec.i: EasyNet/src/net/FixedLengthFrameCodec.cpp.i

.PHONY : EasyNet/src/net/FixedLengthFrameCodec.i

# target to preprocess a source file
EasyNet/src/net/FixedLengthFrameCodec.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/FixedLengthFrameCodec.cpp.i
.PHONY : EasyNet/src/net/FixedLengthFrameCodec.cpp.i

EasyNet/src/net/FixedLengthFrameCodec.s: EasyNet/src/net/FixedLengthFrameCodec.cpp.s

.PHONY : EasyNet/src/net/FixedLengthFrameCodec.s

# target to generate assembly for a file
EasyNet/src/net/FixedLengthFrameCodec.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/FixedLengthFrameCodec.cpp.s
.PHONY : EasyNet/src/net/FixedLengthFrameCodec.cpp.s

EasyNet/src/net/FooService.pb.o: EasyNet/src/net/FooService.pb.cc.o

.PHONY : EasyNet/src/net/FooService.pb.o

# target to build an object file
EasyNet/src/net/FooService.pb.cc.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/FooService.pb.cc.o
.PHONY : EasyNet/src/net/FooService.pb.cc.o

EasyNet/src/net/FooService.pb.i: EasyNet/src/net/FooService.pb.cc.i

.PHONY : EasyNet/src/net/FooService.pb.i

# target to preprocess a source file
EasyNet/src/net/FooService.pb.cc.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/FooService.pb.cc.i
.PHONY : EasyNet/src/net/FooService.pb.cc.i

EasyNet/src/net/FooService.pb.s: EasyNet/src/net/FooService.pb.cc.s

.PHONY : EasyNet/src/net/FooService.pb.s

# target to generate assembly for a file
EasyNet/src/net/FooService.pb.cc.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/FooService.pb.cc.s
.PHONY : EasyNet/src/net/FooService.pb.cc.s

EasyNet/src/net/HttpParser.o: EasyNet/src/net/HttpParser.cpp.o

.PHONY : EasyNet/src/net/HttpParser.o

# target to build an object file
EasyNet/src/net/HttpParser.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpParser.cpp.o
.PHONY : EasyNet/src/net/HttpParser.cpp.o

EasyNet/src/net/HttpParser.i: EasyNet/src/net/HttpParser.cpp.i

.PHONY : EasyNet/src/net/HttpParser.i

# target to preprocess a source file
EasyNet/src/net/HttpParser.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpParser.cpp.i
.PHONY : EasyNet/src/net/HttpParser.cpp.i

EasyNet/src/net/HttpParser.s: EasyNet/src/net/HttpParser.cpp.s

.PHONY : EasyNet/src/net/HttpParser.s

# target to generate assembly for a file
EasyNet/src/net/HttpParser.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpParser.cpp.s
.PHONY : EasyNet/src/net/HttpParser.cpp.s

EasyNet/src/net/HttpRequest.o: EasyNet/src/net/HttpRequest.cpp.o

.PHONY : EasyNet/src/net/HttpRequest.o

# target to build an object file
EasyNet/src/net/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpRequest.cpp.o
.PHONY : EasyNet/src/net/HttpRequest.cpp.o

EasyNet/src/net/HttpRequest.i: EasyNet/src/net/HttpRequest.cpp.i

.PHONY : EasyNet/src/net/HttpRequest.i

# target to preprocess a source file
EasyNet/src/net/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpRequest.cpp.i
.PHONY : EasyNet/src/net/HttpRequest.cpp.i

EasyNet/src/net/HttpRequest.s: EasyNet/src/net/HttpRequest.cpp.s

.PHONY : EasyNet/src/net/HttpRequest.s

# target to generate assembly for a file
EasyNet/src/net/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpRequest.cpp.s
.PHONY : EasyNet/src/net/HttpRequest.cpp.s

EasyNet/src/net/HttpResponse.o: EasyNet/src/net/HttpResponse.cpp.o

.PHONY : EasyNet/src/net/HttpResponse.o

# target to build an object file
EasyNet/src/net/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpResponse.cpp.o
.PHONY : EasyNet/src/net/HttpResponse.cpp.o

EasyNet/src/net/HttpResponse.i: EasyNet/src/net/HttpResponse.cpp.i

.PHONY : EasyNet/src/net/HttpResponse.i

# target to preprocess a source file
EasyNet/src/net/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpResponse.cpp.i
.PHONY : EasyNet/src/net/HttpResponse.cpp.i

EasyNet/src/net/HttpResponse.s: EasyNet/src/net/HttpResponse.cpp.s

.PHONY : EasyNet/src/net/HttpResponse.s

# target to generate assembly for a file
EasyNet/src/net/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpResponse.cpp.s
.PHONY : EasyNet/src/net/HttpResponse.cpp.s

EasyNet/src/net/HttpServer.o: EasyNet/src/net/HttpServer.cpp.o

.PHONY : EasyNet/src/net/HttpServer.o

# target to build an object file
EasyNet/src/net/HttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpServer.cpp.o
.PHONY : EasyNet/src/net/HttpServer.cpp.o

EasyNet/src/net/HttpServer.i: EasyNet/src/net/HttpServer.cpp.i

.PHONY : EasyNet/src/net/HttpServer.i

# target to preprocess a source file
EasyNet/src/net/HttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpServer.cpp.i
.PHONY : EasyNet/src/net/HttpServer.cpp.i

EasyNet/src/net/HttpServer.s: EasyNet/src/net/HttpServer.cpp.s

.PHONY : EasyNet/src/net/HttpServer.s

# target to generate assembly for a file
EasyNet/src/net/HttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/HttpServer.cpp.s
.PHONY : EasyNet/src/net/HttpServer.cpp.s

EasyNet/src/net/InternetAddress.o: EasyNet/src/net/InternetAddress.cpp.o

.PHONY : EasyNet/src/net/InternetAddress.o

# target to build an object file
EasyNet/src/net/InternetAddress.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/InternetAddress.cpp.o
.PHONY : EasyNet/src/net/InternetAddress.cpp.o

EasyNet/src/net/InternetAddress.i: EasyNet/src/net/InternetAddress.cpp.i

.PHONY : EasyNet/src/net/InternetAddress.i

# target to preprocess a source file
EasyNet/src/net/InternetAddress.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/InternetAddress.cpp.i
.PHONY : EasyNet/src/net/InternetAddress.cpp.i

EasyNet/src/net/InternetAddress.s: EasyNet/src/net/InternetAddress.cpp.s

.PHONY : EasyNet/src/net/InternetAddress.s

# target to generate assembly for a file
EasyNet/src/net/InternetAddress.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/InternetAddress.cpp.s
.PHONY : EasyNet/src/net/InternetAddress.cpp.s

EasyNet/src/net/LengthFieldFrameCodec.o: EasyNet/src/net/LengthFieldFrameCodec.cpp.o

.PHONY : EasyNet/src/net/LengthFieldFrameCodec.o

# target to build an object file
EasyNet/src/net/LengthFieldFrameCodec.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/LengthFieldFrameCodec.cpp.o
.PHONY : EasyNet/src/net/LengthFieldFrameCodec.cpp.o

EasyNet/src/net/LengthFieldFrameCodec.i: EasyNet/src/net/LengthFieldFrameCodec.cpp.i

.PHONY : EasyNet/src/net/LengthFieldFrameCodec.i

# target to preprocess a source file
EasyNet/src/net/LengthFieldFrameCodec.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/LengthFieldFrameCodec.cpp.i
.PHONY : EasyNet/src/net/LengthFieldFrameCodec.cpp.i

EasyNet/src/net/LengthFieldFrameCodec.s: EasyNet/src/net/LengthFieldFrameCodec.cpp.s

.PHONY : EasyNet/src/net/LengthFieldFrameCodec.s

# target to generate assembly for a file
EasyNet/src/net/LengthFieldFrameCodec.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/LengthFieldFrameCodec.cpp.s
.PHONY : EasyNet/src/net/LengthFieldFrameCodec.cpp.s

EasyNet/src/net/LineBasedFrameCodec.o: EasyNet/src/net/LineBasedFrameCodec.cpp.o

.PHONY : EasyNet/src/net/LineBasedFrameCodec.o

# target to build an object file
EasyNet/src/net/LineBasedFrameCodec.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/LineBasedFrameCodec.cpp.o
.PHONY : EasyNet/src/net/LineBasedFrameCodec.cpp.o

EasyNet/src/net/LineBasedFrameCodec.i: EasyNet/src/net/LineBasedFrameCodec.cpp.i

.PHONY : EasyNet/src/net/LineBasedFrameCodec.i

# target to preprocess a source file
EasyNet/src/net/LineBasedFrameCodec.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/LineBasedFrameCodec.cpp.i
.PHONY : EasyNet/src/net/LineBasedFrameCodec.cpp.i

EasyNet/src/net/LineBasedFrameCodec.s: EasyNet/src/net/LineBasedFrameCodec.cpp.s

.PHONY : EasyNet/src/net/LineBasedFrameCodec.s

# target to generate assembly for a file
EasyNet/src/net/LineBasedFrameCodec.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/LineBasedFrameCodec.cpp.s
.PHONY : EasyNet/src/net/LineBasedFrameCodec.cpp.s

EasyNet/src/net/NetbaseLightTest.pb.o: EasyNet/src/net/NetbaseLightTest.pb.cc.o

.PHONY : EasyNet/src/net/NetbaseLightTest.pb.o

# target to build an object file
EasyNet/src/net/NetbaseLightTest.pb.cc.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/NetbaseLightTest.pb.cc.o
.PHONY : EasyNet/src/net/NetbaseLightTest.pb.cc.o

EasyNet/src/net/NetbaseLightTest.pb.i: EasyNet/src/net/NetbaseLightTest.pb.cc.i

.PHONY : EasyNet/src/net/NetbaseLightTest.pb.i

# target to preprocess a source file
EasyNet/src/net/NetbaseLightTest.pb.cc.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/NetbaseLightTest.pb.cc.i
.PHONY : EasyNet/src/net/NetbaseLightTest.pb.cc.i

EasyNet/src/net/NetbaseLightTest.pb.s: EasyNet/src/net/NetbaseLightTest.pb.cc.s

.PHONY : EasyNet/src/net/NetbaseLightTest.pb.s

# target to generate assembly for a file
EasyNet/src/net/NetbaseLightTest.pb.cc.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/NetbaseLightTest.pb.cc.s
.PHONY : EasyNet/src/net/NetbaseLightTest.pb.cc.s

EasyNet/src/net/PollerFactory.o: EasyNet/src/net/PollerFactory.cpp.o

.PHONY : EasyNet/src/net/PollerFactory.o

# target to build an object file
EasyNet/src/net/PollerFactory.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/PollerFactory.cpp.o
.PHONY : EasyNet/src/net/PollerFactory.cpp.o

EasyNet/src/net/PollerFactory.i: EasyNet/src/net/PollerFactory.cpp.i

.PHONY : EasyNet/src/net/PollerFactory.i

# target to preprocess a source file
EasyNet/src/net/PollerFactory.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/PollerFactory.cpp.i
.PHONY : EasyNet/src/net/PollerFactory.cpp.i

EasyNet/src/net/PollerFactory.s: EasyNet/src/net/PollerFactory.cpp.s

.PHONY : EasyNet/src/net/PollerFactory.s

# target to generate assembly for a file
EasyNet/src/net/PollerFactory.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/PollerFactory.cpp.s
.PHONY : EasyNet/src/net/PollerFactory.cpp.s

EasyNet/src/net/ProtobufFrameCodec.o: EasyNet/src/net/ProtobufFrameCodec.cpp.o

.PHONY : EasyNet/src/net/ProtobufFrameCodec.o

# target to build an object file
EasyNet/src/net/ProtobufFrameCodec.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/ProtobufFrameCodec.cpp.o
.PHONY : EasyNet/src/net/ProtobufFrameCodec.cpp.o

EasyNet/src/net/ProtobufFrameCodec.i: EasyNet/src/net/ProtobufFrameCodec.cpp.i

.PHONY : EasyNet/src/net/ProtobufFrameCodec.i

# target to preprocess a source file
EasyNet/src/net/ProtobufFrameCodec.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/ProtobufFrameCodec.cpp.i
.PHONY : EasyNet/src/net/ProtobufFrameCodec.cpp.i

EasyNet/src/net/ProtobufFrameCodec.s: EasyNet/src/net/ProtobufFrameCodec.cpp.s

.PHONY : EasyNet/src/net/ProtobufFrameCodec.s

# target to generate assembly for a file
EasyNet/src/net/ProtobufFrameCodec.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/ProtobufFrameCodec.cpp.s
.PHONY : EasyNet/src/net/ProtobufFrameCodec.cpp.s

EasyNet/src/net/Reactor.o: EasyNet/src/net/Reactor.cpp.o

.PHONY : EasyNet/src/net/Reactor.o

# target to build an object file
EasyNet/src/net/Reactor.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Reactor.cpp.o
.PHONY : EasyNet/src/net/Reactor.cpp.o

EasyNet/src/net/Reactor.i: EasyNet/src/net/Reactor.cpp.i

.PHONY : EasyNet/src/net/Reactor.i

# target to preprocess a source file
EasyNet/src/net/Reactor.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Reactor.cpp.i
.PHONY : EasyNet/src/net/Reactor.cpp.i

EasyNet/src/net/Reactor.s: EasyNet/src/net/Reactor.cpp.s

.PHONY : EasyNet/src/net/Reactor.s

# target to generate assembly for a file
EasyNet/src/net/Reactor.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Reactor.cpp.s
.PHONY : EasyNet/src/net/Reactor.cpp.s

EasyNet/src/net/RpcChannel.o: EasyNet/src/net/RpcChannel.cpp.o

.PHONY : EasyNet/src/net/RpcChannel.o

# target to build an object file
EasyNet/src/net/RpcChannel.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcChannel.cpp.o
.PHONY : EasyNet/src/net/RpcChannel.cpp.o

EasyNet/src/net/RpcChannel.i: EasyNet/src/net/RpcChannel.cpp.i

.PHONY : EasyNet/src/net/RpcChannel.i

# target to preprocess a source file
EasyNet/src/net/RpcChannel.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcChannel.cpp.i
.PHONY : EasyNet/src/net/RpcChannel.cpp.i

EasyNet/src/net/RpcChannel.s: EasyNet/src/net/RpcChannel.cpp.s

.PHONY : EasyNet/src/net/RpcChannel.s

# target to generate assembly for a file
EasyNet/src/net/RpcChannel.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcChannel.cpp.s
.PHONY : EasyNet/src/net/RpcChannel.cpp.s

EasyNet/src/net/RpcMessage.pb.o: EasyNet/src/net/RpcMessage.pb.cc.o

.PHONY : EasyNet/src/net/RpcMessage.pb.o

# target to build an object file
EasyNet/src/net/RpcMessage.pb.cc.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcMessage.pb.cc.o
.PHONY : EasyNet/src/net/RpcMessage.pb.cc.o

EasyNet/src/net/RpcMessage.pb.i: EasyNet/src/net/RpcMessage.pb.cc.i

.PHONY : EasyNet/src/net/RpcMessage.pb.i

# target to preprocess a source file
EasyNet/src/net/RpcMessage.pb.cc.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcMessage.pb.cc.i
.PHONY : EasyNet/src/net/RpcMessage.pb.cc.i

EasyNet/src/net/RpcMessage.pb.s: EasyNet/src/net/RpcMessage.pb.cc.s

.PHONY : EasyNet/src/net/RpcMessage.pb.s

# target to generate assembly for a file
EasyNet/src/net/RpcMessage.pb.cc.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcMessage.pb.cc.s
.PHONY : EasyNet/src/net/RpcMessage.pb.cc.s

EasyNet/src/net/RpcServer.o: EasyNet/src/net/RpcServer.cpp.o

.PHONY : EasyNet/src/net/RpcServer.o

# target to build an object file
EasyNet/src/net/RpcServer.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcServer.cpp.o
.PHONY : EasyNet/src/net/RpcServer.cpp.o

EasyNet/src/net/RpcServer.i: EasyNet/src/net/RpcServer.cpp.i

.PHONY : EasyNet/src/net/RpcServer.i

# target to preprocess a source file
EasyNet/src/net/RpcServer.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcServer.cpp.i
.PHONY : EasyNet/src/net/RpcServer.cpp.i

EasyNet/src/net/RpcServer.s: EasyNet/src/net/RpcServer.cpp.s

.PHONY : EasyNet/src/net/RpcServer.s

# target to generate assembly for a file
EasyNet/src/net/RpcServer.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/RpcServer.cpp.s
.PHONY : EasyNet/src/net/RpcServer.cpp.s

EasyNet/src/net/SelectPoller.o: EasyNet/src/net/SelectPoller.cpp.o

.PHONY : EasyNet/src/net/SelectPoller.o

# target to build an object file
EasyNet/src/net/SelectPoller.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/SelectPoller.cpp.o
.PHONY : EasyNet/src/net/SelectPoller.cpp.o

EasyNet/src/net/SelectPoller.i: EasyNet/src/net/SelectPoller.cpp.i

.PHONY : EasyNet/src/net/SelectPoller.i

# target to preprocess a source file
EasyNet/src/net/SelectPoller.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/SelectPoller.cpp.i
.PHONY : EasyNet/src/net/SelectPoller.cpp.i

EasyNet/src/net/SelectPoller.s: EasyNet/src/net/SelectPoller.cpp.s

.PHONY : EasyNet/src/net/SelectPoller.s

# target to generate assembly for a file
EasyNet/src/net/SelectPoller.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/SelectPoller.cpp.s
.PHONY : EasyNet/src/net/SelectPoller.cpp.s

EasyNet/src/net/Socket.o: EasyNet/src/net/Socket.cpp.o

.PHONY : EasyNet/src/net/Socket.o

# target to build an object file
EasyNet/src/net/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Socket.cpp.o
.PHONY : EasyNet/src/net/Socket.cpp.o

EasyNet/src/net/Socket.i: EasyNet/src/net/Socket.cpp.i

.PHONY : EasyNet/src/net/Socket.i

# target to preprocess a source file
EasyNet/src/net/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Socket.cpp.i
.PHONY : EasyNet/src/net/Socket.cpp.i

EasyNet/src/net/Socket.s: EasyNet/src/net/Socket.cpp.s

.PHONY : EasyNet/src/net/Socket.s

# target to generate assembly for a file
EasyNet/src/net/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/Socket.cpp.s
.PHONY : EasyNet/src/net/Socket.cpp.s

EasyNet/src/net/SocketApiWrapper.o: EasyNet/src/net/SocketApiWrapper.cpp.o

.PHONY : EasyNet/src/net/SocketApiWrapper.o

# target to build an object file
EasyNet/src/net/SocketApiWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/SocketApiWrapper.cpp.o
.PHONY : EasyNet/src/net/SocketApiWrapper.cpp.o

EasyNet/src/net/SocketApiWrapper.i: EasyNet/src/net/SocketApiWrapper.cpp.i

.PHONY : EasyNet/src/net/SocketApiWrapper.i

# target to preprocess a source file
EasyNet/src/net/SocketApiWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/SocketApiWrapper.cpp.i
.PHONY : EasyNet/src/net/SocketApiWrapper.cpp.i

EasyNet/src/net/SocketApiWrapper.s: EasyNet/src/net/SocketApiWrapper.cpp.s

.PHONY : EasyNet/src/net/SocketApiWrapper.s

# target to generate assembly for a file
EasyNet/src/net/SocketApiWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/SocketApiWrapper.cpp.s
.PHONY : EasyNet/src/net/SocketApiWrapper.cpp.s

EasyNet/src/net/TcpClient.o: EasyNet/src/net/TcpClient.cpp.o

.PHONY : EasyNet/src/net/TcpClient.o

# target to build an object file
EasyNet/src/net/TcpClient.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpClient.cpp.o
.PHONY : EasyNet/src/net/TcpClient.cpp.o

EasyNet/src/net/TcpClient.i: EasyNet/src/net/TcpClient.cpp.i

.PHONY : EasyNet/src/net/TcpClient.i

# target to preprocess a source file
EasyNet/src/net/TcpClient.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpClient.cpp.i
.PHONY : EasyNet/src/net/TcpClient.cpp.i

EasyNet/src/net/TcpClient.s: EasyNet/src/net/TcpClient.cpp.s

.PHONY : EasyNet/src/net/TcpClient.s

# target to generate assembly for a file
EasyNet/src/net/TcpClient.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpClient.cpp.s
.PHONY : EasyNet/src/net/TcpClient.cpp.s

EasyNet/src/net/TcpConnection.o: EasyNet/src/net/TcpConnection.cpp.o

.PHONY : EasyNet/src/net/TcpConnection.o

# target to build an object file
EasyNet/src/net/TcpConnection.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpConnection.cpp.o
.PHONY : EasyNet/src/net/TcpConnection.cpp.o

EasyNet/src/net/TcpConnection.i: EasyNet/src/net/TcpConnection.cpp.i

.PHONY : EasyNet/src/net/TcpConnection.i

# target to preprocess a source file
EasyNet/src/net/TcpConnection.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpConnection.cpp.i
.PHONY : EasyNet/src/net/TcpConnection.cpp.i

EasyNet/src/net/TcpConnection.s: EasyNet/src/net/TcpConnection.cpp.s

.PHONY : EasyNet/src/net/TcpConnection.s

# target to generate assembly for a file
EasyNet/src/net/TcpConnection.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpConnection.cpp.s
.PHONY : EasyNet/src/net/TcpConnection.cpp.s

EasyNet/src/net/TcpConnector.o: EasyNet/src/net/TcpConnector.cpp.o

.PHONY : EasyNet/src/net/TcpConnector.o

# target to build an object file
EasyNet/src/net/TcpConnector.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpConnector.cpp.o
.PHONY : EasyNet/src/net/TcpConnector.cpp.o

EasyNet/src/net/TcpConnector.i: EasyNet/src/net/TcpConnector.cpp.i

.PHONY : EasyNet/src/net/TcpConnector.i

# target to preprocess a source file
EasyNet/src/net/TcpConnector.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpConnector.cpp.i
.PHONY : EasyNet/src/net/TcpConnector.cpp.i

EasyNet/src/net/TcpConnector.s: EasyNet/src/net/TcpConnector.cpp.s

.PHONY : EasyNet/src/net/TcpConnector.s

# target to generate assembly for a file
EasyNet/src/net/TcpConnector.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpConnector.cpp.s
.PHONY : EasyNet/src/net/TcpConnector.cpp.s

EasyNet/src/net/TcpServer.o: EasyNet/src/net/TcpServer.cpp.o

.PHONY : EasyNet/src/net/TcpServer.o

# target to build an object file
EasyNet/src/net/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpServer.cpp.o
.PHONY : EasyNet/src/net/TcpServer.cpp.o

EasyNet/src/net/TcpServer.i: EasyNet/src/net/TcpServer.cpp.i

.PHONY : EasyNet/src/net/TcpServer.i

# target to preprocess a source file
EasyNet/src/net/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpServer.cpp.i
.PHONY : EasyNet/src/net/TcpServer.cpp.i

EasyNet/src/net/TcpServer.s: EasyNet/src/net/TcpServer.cpp.s

.PHONY : EasyNet/src/net/TcpServer.s

# target to generate assembly for a file
EasyNet/src/net/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TcpServer.cpp.s
.PHONY : EasyNet/src/net/TcpServer.cpp.s

EasyNet/src/net/TimerLoopThread.o: EasyNet/src/net/TimerLoopThread.cpp.o

.PHONY : EasyNet/src/net/TimerLoopThread.o

# target to build an object file
EasyNet/src/net/TimerLoopThread.cpp.o:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TimerLoopThread.cpp.o
.PHONY : EasyNet/src/net/TimerLoopThread.cpp.o

EasyNet/src/net/TimerLoopThread.i: EasyNet/src/net/TimerLoopThread.cpp.i

.PHONY : EasyNet/src/net/TimerLoopThread.i

# target to preprocess a source file
EasyNet/src/net/TimerLoopThread.cpp.i:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TimerLoopThread.cpp.i
.PHONY : EasyNet/src/net/TimerLoopThread.cpp.i

EasyNet/src/net/TimerLoopThread.s: EasyNet/src/net/TimerLoopThread.cpp.s

.PHONY : EasyNet/src/net/TimerLoopThread.s

# target to generate assembly for a file
EasyNet/src/net/TimerLoopThread.cpp.s:
	$(MAKE) -f CMakeFiles/EasyNet.dir/build.make CMakeFiles/EasyNet.dir/EasyNet/src/net/TimerLoopThread.cpp.s
.PHONY : EasyNet/src/net/TimerLoopThread.cpp.s

EasyNet/src/ut/ChatClient.o: EasyNet/src/ut/ChatClient.cpp.o

.PHONY : EasyNet/src/ut/ChatClient.o

# target to build an object file
EasyNet/src/ut/ChatClient.cpp.o:
	$(MAKE) -f CMakeFiles/ChatClient.dir/build.make CMakeFiles/ChatClient.dir/EasyNet/src/ut/ChatClient.cpp.o
.PHONY : EasyNet/src/ut/ChatClient.cpp.o

EasyNet/src/ut/ChatClient.i: EasyNet/src/ut/ChatClient.cpp.i

.PHONY : EasyNet/src/ut/ChatClient.i

# target to preprocess a source file
EasyNet/src/ut/ChatClient.cpp.i:
	$(MAKE) -f CMakeFiles/ChatClient.dir/build.make CMakeFiles/ChatClient.dir/EasyNet/src/ut/ChatClient.cpp.i
.PHONY : EasyNet/src/ut/ChatClient.cpp.i

EasyNet/src/ut/ChatClient.s: EasyNet/src/ut/ChatClient.cpp.s

.PHONY : EasyNet/src/ut/ChatClient.s

# target to generate assembly for a file
EasyNet/src/ut/ChatClient.cpp.s:
	$(MAKE) -f CMakeFiles/ChatClient.dir/build.make CMakeFiles/ChatClient.dir/EasyNet/src/ut/ChatClient.cpp.s
.PHONY : EasyNet/src/ut/ChatClient.cpp.s

EasyNet/src/ut/ChatServer.o: EasyNet/src/ut/ChatServer.cpp.o

.PHONY : EasyNet/src/ut/ChatServer.o

# target to build an object file
EasyNet/src/ut/ChatServer.cpp.o:
	$(MAKE) -f CMakeFiles/ChatServer.dir/build.make CMakeFiles/ChatServer.dir/EasyNet/src/ut/ChatServer.cpp.o
.PHONY : EasyNet/src/ut/ChatServer.cpp.o

EasyNet/src/ut/ChatServer.i: EasyNet/src/ut/ChatServer.cpp.i

.PHONY : EasyNet/src/ut/ChatServer.i

# target to preprocess a source file
EasyNet/src/ut/ChatServer.cpp.i:
	$(MAKE) -f CMakeFiles/ChatServer.dir/build.make CMakeFiles/ChatServer.dir/EasyNet/src/ut/ChatServer.cpp.i
.PHONY : EasyNet/src/ut/ChatServer.cpp.i

EasyNet/src/ut/ChatServer.s: EasyNet/src/ut/ChatServer.cpp.s

.PHONY : EasyNet/src/ut/ChatServer.s

# target to generate assembly for a file
EasyNet/src/ut/ChatServer.cpp.s:
	$(MAKE) -f CMakeFiles/ChatServer.dir/build.make CMakeFiles/ChatServer.dir/EasyNet/src/ut/ChatServer.cpp.s
.PHONY : EasyNet/src/ut/ChatServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... EasyNet"
	@echo "... ChatClient"
	@echo "... ChatServer"
	@echo "... EasyNet/src/base/Condition.o"
	@echo "... EasyNet/src/base/Condition.i"
	@echo "... EasyNet/src/base/Condition.s"
	@echo "... EasyNet/src/base/MutexLock.o"
	@echo "... EasyNet/src/base/MutexLock.i"
	@echo "... EasyNet/src/base/MutexLock.s"
	@echo "... EasyNet/src/base/Thread.o"
	@echo "... EasyNet/src/base/Thread.i"
	@echo "... EasyNet/src/base/Thread.s"
	@echo "... EasyNet/src/base/TimeStamp.o"
	@echo "... EasyNet/src/base/TimeStamp.i"
	@echo "... EasyNet/src/base/TimeStamp.s"
	@echo "... EasyNet/src/net/Acceptor.o"
	@echo "... EasyNet/src/net/Acceptor.i"
	@echo "... EasyNet/src/net/Acceptor.s"
	@echo "... EasyNet/src/net/Channel.o"
	@echo "... EasyNet/src/net/Channel.i"
	@echo "... EasyNet/src/net/Channel.s"
	@echo "... EasyNet/src/net/ChannelBuffer.o"
	@echo "... EasyNet/src/net/ChannelBuffer.i"
	@echo "... EasyNet/src/net/ChannelBuffer.s"
	@echo "... EasyNet/src/net/EventLoop.o"
	@echo "... EasyNet/src/net/EventLoop.i"
	@echo "... EasyNet/src/net/EventLoop.s"
	@echo "... EasyNet/src/net/EventLoopThread.o"
	@echo "... EasyNet/src/net/EventLoopThread.i"
	@echo "... EasyNet/src/net/EventLoopThread.s"
	@echo "... EasyNet/src/net/EventLoopThreadGroup.o"
	@echo "... EasyNet/src/net/EventLoopThreadGroup.i"
	@echo "... EasyNet/src/net/EventLoopThreadGroup.s"
	@echo "... EasyNet/src/net/FixedLengthFrameCodec.o"
	@echo "... EasyNet/src/net/FixedLengthFrameCodec.i"
	@echo "... EasyNet/src/net/FixedLengthFrameCodec.s"
	@echo "... EasyNet/src/net/FooService.pb.o"
	@echo "... EasyNet/src/net/FooService.pb.i"
	@echo "... EasyNet/src/net/FooService.pb.s"
	@echo "... EasyNet/src/net/HttpParser.o"
	@echo "... EasyNet/src/net/HttpParser.i"
	@echo "... EasyNet/src/net/HttpParser.s"
	@echo "... EasyNet/src/net/HttpRequest.o"
	@echo "... EasyNet/src/net/HttpRequest.i"
	@echo "... EasyNet/src/net/HttpRequest.s"
	@echo "... EasyNet/src/net/HttpResponse.o"
	@echo "... EasyNet/src/net/HttpResponse.i"
	@echo "... EasyNet/src/net/HttpResponse.s"
	@echo "... EasyNet/src/net/HttpServer.o"
	@echo "... EasyNet/src/net/HttpServer.i"
	@echo "... EasyNet/src/net/HttpServer.s"
	@echo "... EasyNet/src/net/InternetAddress.o"
	@echo "... EasyNet/src/net/InternetAddress.i"
	@echo "... EasyNet/src/net/InternetAddress.s"
	@echo "... EasyNet/src/net/LengthFieldFrameCodec.o"
	@echo "... EasyNet/src/net/LengthFieldFrameCodec.i"
	@echo "... EasyNet/src/net/LengthFieldFrameCodec.s"
	@echo "... EasyNet/src/net/LineBasedFrameCodec.o"
	@echo "... EasyNet/src/net/LineBasedFrameCodec.i"
	@echo "... EasyNet/src/net/LineBasedFrameCodec.s"
	@echo "... EasyNet/src/net/NetbaseLightTest.pb.o"
	@echo "... EasyNet/src/net/NetbaseLightTest.pb.i"
	@echo "... EasyNet/src/net/NetbaseLightTest.pb.s"
	@echo "... EasyNet/src/net/PollerFactory.o"
	@echo "... EasyNet/src/net/PollerFactory.i"
	@echo "... EasyNet/src/net/PollerFactory.s"
	@echo "... EasyNet/src/net/ProtobufFrameCodec.o"
	@echo "... EasyNet/src/net/ProtobufFrameCodec.i"
	@echo "... EasyNet/src/net/ProtobufFrameCodec.s"
	@echo "... EasyNet/src/net/Reactor.o"
	@echo "... EasyNet/src/net/Reactor.i"
	@echo "... EasyNet/src/net/Reactor.s"
	@echo "... EasyNet/src/net/RpcChannel.o"
	@echo "... EasyNet/src/net/RpcChannel.i"
	@echo "... EasyNet/src/net/RpcChannel.s"
	@echo "... EasyNet/src/net/RpcMessage.pb.o"
	@echo "... EasyNet/src/net/RpcMessage.pb.i"
	@echo "... EasyNet/src/net/RpcMessage.pb.s"
	@echo "... EasyNet/src/net/RpcServer.o"
	@echo "... EasyNet/src/net/RpcServer.i"
	@echo "... EasyNet/src/net/RpcServer.s"
	@echo "... EasyNet/src/net/SelectPoller.o"
	@echo "... EasyNet/src/net/SelectPoller.i"
	@echo "... EasyNet/src/net/SelectPoller.s"
	@echo "... EasyNet/src/net/Socket.o"
	@echo "... EasyNet/src/net/Socket.i"
	@echo "... EasyNet/src/net/Socket.s"
	@echo "... EasyNet/src/net/SocketApiWrapper.o"
	@echo "... EasyNet/src/net/SocketApiWrapper.i"
	@echo "... EasyNet/src/net/SocketApiWrapper.s"
	@echo "... EasyNet/src/net/TcpClient.o"
	@echo "... EasyNet/src/net/TcpClient.i"
	@echo "... EasyNet/src/net/TcpClient.s"
	@echo "... EasyNet/src/net/TcpConnection.o"
	@echo "... EasyNet/src/net/TcpConnection.i"
	@echo "... EasyNet/src/net/TcpConnection.s"
	@echo "... EasyNet/src/net/TcpConnector.o"
	@echo "... EasyNet/src/net/TcpConnector.i"
	@echo "... EasyNet/src/net/TcpConnector.s"
	@echo "... EasyNet/src/net/TcpServer.o"
	@echo "... EasyNet/src/net/TcpServer.i"
	@echo "... EasyNet/src/net/TcpServer.s"
	@echo "... EasyNet/src/net/TimerLoopThread.o"
	@echo "... EasyNet/src/net/TimerLoopThread.i"
	@echo "... EasyNet/src/net/TimerLoopThread.s"
	@echo "... EasyNet/src/ut/ChatClient.o"
	@echo "... EasyNet/src/ut/ChatClient.i"
	@echo "... EasyNet/src/ut/ChatClient.s"
	@echo "... EasyNet/src/ut/ChatServer.o"
	@echo "... EasyNet/src/ut/ChatServer.i"
	@echo "... EasyNet/src/ut/ChatServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

